# Generated by Django 5.0.2 on 2024-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время платежа'),
        ),
    ]
