# Generated by Django 5.0.2 on 2024-04-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_analyzer', '0002_alter_transaction_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='dt',
            new_name='date',
        ),
    ]
